language: java
matrix: 
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
#    - os: linux
#      jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
node_js: "10"
install: 
  - ./gradlew assemble --warning-mode all
  - ./gradlew dependencies -q
  - npm install -g snyk
script: 
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - snyk test --file=build.gradle --gradle-sub-project=alarmclock
  - snyk monitor --org=mleegwt --file=build.gradle --gradle-sub-project=alarmclock
  - fossa init
  - fossa analyze
